version: 3.10.2.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2019
configuration: Release
platform: Any CPU
force_https_clone: true
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST: https://www.nuget.org
  NUGET_APIKEY: 
    secure: LBjemyCw2u3Vp5qprTPynswwuvMwydNpGNwNeiycZbbYIAj/+4RFpxbVJirfWmIk
build: off
build_script:
- ps: >-
    dotnet build .\Api.sln;
test: off
test_script:
- ps: >-
    dotnet test .\.tests\Api.UnitTests\Api.UnitTests.csproj
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
- path: '**\*.snupkg'
  name: NuGet Symbol Package
deploy:
- provider: NuGet
  server: $(NUGET_HOST)
  api_key: $(NUGET_APIKEY)
  on:
    branch: master
